setwd("C:/Users/test1/OneDrive/Documents 201617/R/gganimate")
library(tidyverse)
library(ggplot2)
library(gganimate)
library(gifski)
library(png)
BP7phyla=read.table("BP7_phyla.csv",header=T,sep=",", strip.white = TRUE)
head(as.data.frame(BP7phyla), n = 12)
BP7phyla_long=gather(BP7phyla, "Genus", "Counts", 4:15)
head(as.data.frame(BP7phyla_long), n = 12)
